ELearning/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class MainPageController : Controller
    {
        // GET: MainPage
        [HttpGet]
        public ActionResult Main()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Note()
        {
            return Redirect("mailto:marcinszydlak93@wp.pl");
        }
        [HttpGet]
        public ActionResult About()
        {
            return View();
        }
    }
}

ELearning/Controllers/StudentController.cs
using DataServices.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataServices;

namespace ELearning.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student

        [HttpGet]
        public ActionResult Index(UserLoginModel model)
        {

            LoggedUserModel user = new LoggedUserModel();
            UserServices services = new UserServices();
            if(Session["zalogowany"] != null && Request.Cookies["LoggedUser"] !=null && model.Login == null && model.Password == null)
            {
                user.Login = Request.Cookies["LoggedUser"].Values.Get("Login");
                user.Name = Request.Cookies["LoggedUser"].Values.Get("Name");
                user.Surname = Request.Cookies["LoggedUser"].Values.Get("Surname");
            }
            else
            {
                user.Login = model.Login;
                user.Name = model.Name;
                user.Surname = model.Surname;
            }
            return View(user);
        }
        [HttpGet]
        public ActionResult EditStudent()
        {
            HttpCookie loggedStudent = Request.Cookies["LoggedUser"];
            StudentModel student = new StudentModel();
            UserServices services = new UserServices();

            
            student = services.GetStudent(loggedStudent.Values.Get("Login"));
            student.Oddziały = services.GetClasses();
            return View(student);
        }
        [HttpPost]
        public ActionResult EditStudent(StudentModel model)
        {
            HttpCookie loggedStudent = Request.Cookies["LoggedUser"];
            UserServices services = new UserServices();
            StudentModel student = services.GetStudent(loggedStudent.Values.Get("Login"));
            services.ChangePassword(student.Login, student.Name, student.Surname, model.Password);

            UserLoginModel logged = new UserLoginModel();
            logged.Login = student.Login;
            logged.Name = student.Name;
            logged.Surname = student.Surname;
            return RedirectToAction("Index",logged);
        }
        [HttpGet]
        public ActionResult ManageCourses()
        {
            CourseServices cs = new CourseServices();
            UserServices us = new UserServices();
            List<CourseModel> courses = new List<CourseModel>();
            HttpCookie loggedStudent = Request.Cookies["LoggedUser"];
            StudentModel student = us.GetStudent(loggedStudent.Values.Get("Login"));
            courses = cs.GetCourses().Where(x => x.ClassId == student.IdKlasy).ToList();
            return View(courses);
        }
        [HttpGet]
        public ActionResult TaskList(int CourseId)
        {
            CourseServices cs = new CourseServices();
            List<TaskModel> tasks = cs.GetTasks(CourseId);
            return View(tasks);
        }
        [HttpGet]
        public ActionResult InsertSolution(int TaskId)
        {
            HttpCookie cookie = new HttpCookie("Solution");
            cookie.Values.Add("TaskId", TaskId.ToString());
            cookie.Expires = DateTime.Now.AddMinutes(2);
            Response.Cookies.Add(cookie);
            return View();
        }
        [HttpPost]
        public ActionResult InsertSolution(SolutionModel model,HttpPostedFileBase upload)
        {
            CourseServices cs = new CourseServices();
            UserServices us = new UserServices();
            HttpCookie loggedStudent = Request.Cookies["LoggedUser"];
            model.Student = us.GetStudent(loggedStudent.Values.Get("Login"));
            model.StudentId = model.Student.IdUcznia;
            model.FileName = upload.FileName;
            using (var reader = new System.IO.BinaryReader(upload.InputStream))
            {
                model.Solution = reader.ReadBytes(upload.ContentLength);
            }
            cs.NewSolution(model);

            return RedirectToAction("ManageCourses","Student");
        }
        [HttpGet]
        public ActionResult SolutionEdit(int TaskId)
        {
            CourseServices cs = new CourseServices();
            UserServices us = new UserServices();
            HttpCookie cookie = Request.Cookies.Get("LoggedUser");
            cookie.Values.Get("Name");
            cookie.Values.Get("Surname");
            cookie.Values.Get("Login");
            StudentModel student = new StudentModel();
            student = us.GetStudent(cookie.Values.Get("Login"));
            SolutionModel solution = new SolutionModel();
            solution = cs.GetSolution(TaskId,student);
            return View(solution);
        }
        [HttpPost]
        public ActionResult SolutionEdit(SolutionModel model, HttpPostedFileBase upload)
        {
            CourseServices cs = new CourseServices();
            UserServices us = new UserServices();
            HttpCookie loggedStudent = Request.Cookies["LoggedUser"];
            model.Student = us.GetStudent(loggedStudent.Values.Get("Login"));
            model.StudentId = model.Student.IdUcznia;
            model.FileName = upload.FileName;
            using (var reader = new System.IO.BinaryReader(upload.InputStream))
            {
                model.Solution = reader.ReadBytes(upload.ContentLength);
            }
            cs.SolutionEdit(model);
            return RedirectToAction("TaskList", new { CourseId = cs.GetTask(model.TaskId).CourseId });
        }

        [HttpGet]
        public ActionResult StudentSolution(int TaskId)
        {
            CourseServices cs = new CourseServices();
            UserServices us = new UserServices();
            HttpCookie cookie = Request.Cookies.Get("LoggedUser");
            cookie.Values.Get("Name");
            cookie.Values.Get("Surname");
            cookie.Values.Get("Login");
            StudentModel student = new StudentModel();
            student = us.GetStudent(cookie.Values.Get("Login"));
            SolutionModel solution = new SolutionModel();
            solution = cs.GetSolution(TaskId, student);
            return View(solution);
        }
        [HttpGet]
        public FileContentResult Download(int SolutionId)
        {
            CourseServices cs = new CourseServices();
            SolutionModel model = new SolutionModel();
            model = cs.GetSolution(SolutionId);
            FileServices fs = new FileServices();
            string ContentType = fs.GetContentType(model.Extension);
            return File(model.Solution, ContentType, model.FileName);
        }
    }
}

ELearning/Controllers/TeacherController.cs
using DataServices;
using DataServices.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        [HttpGet]
        public ActionResult Index(UserLoginModel model)
        {
            LoggedUserModel user = new LoggedUserModel();
            UserServices services = new UserServices();
            if (Session["zalogowany"] != null && Request.Cookies["LoggedUser"] != null && model.Login == null && model.Password == null)
            {
                user.Login = Request.Cookies["LoggedUser"].Values.Get("Login");
                user.Name = Request.Cookies["LoggedUser"].Values.Get("Name");
                user.Surname = Request.Cookies["LoggedUser"].Values.Get("Surname");
            }
            else
            {
                user.Login = model.Login;
                user.Name = model.Name;
                user.Surname = model.Surname;
            }
            return View(user);
        }
        [HttpGet]
        public ActionResult EditTeacher()
        {
            HttpCookie loggedTeacher = Request.Cookies["LoggedUser"];
            TeacherModel teacher = new TeacherModel();
            UserServices services = new UserServices();


            teacher = services.GetTeacher(loggedTeacher.Values.Get("Login"));
            return View(teacher);
        }
        [HttpPost]
        public ActionResult EditTeacher(TeacherModel model)
        {
            HttpCookie loggedTeacher = Request.Cookies["LoggedUser"];
            UserServices services = new UserServices();
            TeacherModel teacher = services.GetTeacher(loggedTeacher.Values.Get("Login"));
            services.ChangePassword(teacher.Login, teacher.Imię, teacher.Nazwisko, model.Hasło);

            UserLoginModel logged = new UserLoginModel();
            logged.Login = model.Login;
            logged.Name = model.Imię;
            logged.Surname = model.Nazwisko;
            return RedirectToAction("Index", logged);
        }
        [HttpGet]
        public ActionResult CreateCourse()
        {
            CourseModel model = new CourseModel();
            CourseServices ServiceForCourses = new CourseServices();
            UserServices ServicesForUsers = new UserServices();
            model.Subjects = ServiceForCourses.GetSubjects();
            model.Classes = ServicesForUsers.GetClasses();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateCourse(CourseModel newCourse)
        {
            CourseServices CourseServ = new CourseServices();
            UserServices UserServ = new UserServices();
            HttpCookie loggedTeacher = Request.Cookies["LoggedUser"];
            TeacherModel teacher = UserServ.GetTeacher(loggedTeacher.Values.Get("Login"));
            newCourse.TeacherId = teacher.IdNauczyciela;
            CourseServ.NewCourse(newCourse);
            return RedirectToAction("Index", "Teacher");
        }
        [HttpGet]
        public ActionResult ManageCourses()
        {
            List<CourseModel> courses = new List<CourseModel>();
            CourseServices CourseServ = new CourseServices();
            UserServices UserServ = new UserServices();
            HttpCookie loggedTeacher = Request.Cookies["LoggedUser"];
            TeacherModel teacher = UserServ.GetTeacher(loggedTeacher.Values.Get("Login"));
            courses = CourseServ.GetCourses(teacher.IdNauczyciela);
            return View(courses);
        }


    }
}

ELearning/Views/Shared/Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Learning", "Main", "MainPage", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Administracja", "Index", "DatabaseAction")</li>
                    @if(Session["admin"]!=null)
                    { 
                    <li>@Html.ActionLink("Zarządzaj uczniami w bazie danych", "ManageStudents")</li>
                    <li>@Html.ActionLink("Zarządzaj nauczycielami w bazie danych", "ManageTeachers")</li>
                    <li>@Html.ActionLink("Zarządzaj klasami w bazie danych", "ManageClasses")</li>
                    <li>@Html.ActionLink("Wyloguj się", "Logout", "DatabaseAction")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Zaloguj się", "Index", "Login")</li>
                    }
                    


                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()


        <hr/>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer>
        <p class="col-md-offset-5">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>
</html>

ELearning/Views/Shared/Student.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Learning", "Main", "MainPage", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if(Session["zalogowany"]!=null)
                    {
                        <li>@Html.ActionLink("Zmień dane profilowe", "EditStudent", "Student")</li>
                        <li>@Html.ActionLink("Przeglądaj swoje kursy", "ManageCourses", "Student")</li>
                        <li>@Html.ActionLink("Wyloguj się", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Administracja", "Index", "DatabaseAction")</li>
                        <li>@Html.ActionLink("Zaloguj się", "Index", "Login")</li>
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr/>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer>
        <p class="col-md-offset-5">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>
</html>

ELearning/Views/Shared/Teacher.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Learning", "Main", "MainPage", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if(Session["zalogowany"]!=null)
                    {
                        <li>@Html.ActionLink("Dodaj nowy kurs", "CreateCourse", "Teacher")</li>
                        <li>@Html.ActionLink("Zmień dane profilowe", "EditTeacher", "Teacher")</li>
                        <li>@Html.ActionLink("Przeglądaj swoje kursy", "ManageCourses", "Teacher")</li>
                        <li>@Html.ActionLink("Wyloguj się", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Administracja", "Index", "DatabaseAction")</li>
                        <li>@Html.ActionLink("Zaloguj się", "Index", "Login")</li>
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr/>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer>
        <p class="col-md-offset-5">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>
</html>

ELearning/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

ELearning/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

ELearning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Learning", "Main", "MainPage", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Administracja", "Index", "DatabaseAction")</li>
                    @if(Session["zalogowany"]!=null)
                    {
                        <li>@Html.ActionLink("Kursy", "#", "#")</li>
                        <li>@Html.ActionLink("Wyloguj się", "Logout", "Login")</li>
                    }
                    else
                    {
                        if (Session["admin"] != null && Request.Cookies["Admin"] != null)
                        {
                            <li>@Html.ActionLink("Zarządzaj uczniami w bazie danych", "ManageStudents")</li>
                            <li>@Html.ActionLink("Zarządzaj nauczycielami w bazie danych", "ManageTeachers")</li>
                            <li>@Html.ActionLink("Zmień dane dotyczące klasy", "UpdateClass")</li>
                        }
                        else
                        { 
                        <li>@Html.ActionLink("Zaloguj się", "Index", "Login")</li>
                        }
                    }
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @if (Session["zalogowany"] != null && Request.Cookies["LoggedUser"]!=null)
        {
            <div class="navbar-left">
                <ul class="nav nav-pills nav-stacked">
                    <li role="presentation">@Html.ActionLink("Zmień dane profilowe","EditStudent","Student")</li>
                    <li role="presentation">@Html.ActionLink("Przeglądaj swoje kursy","#","#")</li>
                    <li role="presentation">@Html.ActionLink("Podgląd ocen","#","#")</li>
                </ul>
            </div>
        }
        else
        {
            if(Session["admin"] == null && Request.Cookies["Admin"]==null && Session["zalogowany"] != null && Request.Cookies["LoggedUser"] != null) 
            {
                <div>Nie masz uprawnień aby oglądać zawartość</div>
            }
        }
        <hr/>

    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <footer>
        <p class="col-md-offset-5">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</body>
</html>